use_frameworks!

platform :ios, '8.0'

target 'SYRemoteLogger_Example' do
  pod 'SYRemoteLogger', :path => '../'

  target 'SYRemoteLogger_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
